# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '294C60E13B7577DAF5E2292C279A9C5A'

_lr_action_items = {'NEWLINE':([0,2,4,5,6,7,9,12,13,15,21,23,24,28,29,31,],[7,7,-6,-5,-8,-7,-4,-9,14,-10,7,-11,26,-12,7,-13,]),'INDENT':([14,26,],[21,29,]),'DEDENT':([2,4,5,6,7,9,10,12,15,23,25,28,30,31,],[-2,-6,-5,-8,-7,-4,-3,-9,-10,-11,28,-12,31,-13,]),'TAGOPEN':([0,2,4,5,6,7,9,12,13,15,16,17,19,21,23,24,28,29,31,],[8,8,-6,-5,-8,-7,-4,-9,8,-10,-18,-19,8,8,-11,8,-12,8,-13,]),'TAGARGSEP':([11,12,15,16,17,18,19,20,22,23,27,28,31,],[13,-9,-10,-18,-19,-14,-16,24,-17,-11,-15,-12,-13,]),'TAGCLOSE':([11,12,13,15,16,17,18,19,20,22,23,27,28,31,],[12,-9,15,-10,-18,-19,-14,-16,23,-17,-11,-15,-12,-13,]),'TEXT':([0,2,4,5,6,7,9,12,13,15,16,17,19,21,23,24,28,29,31,],[4,4,-6,-5,-8,-7,-4,-9,16,-10,-18,-19,16,4,-11,16,-12,4,-13,]),'TAGNAME':([8,],[11,]),'$end':([1,2,3,4,5,6,7,9,10,12,15,23,28,31,],[0,-2,-1,-6,-5,-8,-7,-4,-3,-9,-10,-11,-12,-13,]),'POSSIBLEINDENT':([0,2,4,5,6,7,9,12,15,21,23,28,29,31,],[6,6,-6,-5,-8,-7,-4,-9,-10,6,-11,-12,6,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,],[1,]),'blockcontent':([0,2,21,29,],[2,2,2,2,]),'arg':([13,19,24,],[18,22,27,]),'argpart':([13,19,24,],[19,19,19,]),'block':([0,2,21,29,],[3,10,25,30,]),'text':([0,2,21,29,],[9,9,9,9,]),'tag':([0,2,13,19,21,24,29,],[5,5,17,17,5,17,5,]),'arglist':([13,],[20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> block','document',1,'p_document','_parser.py',12),
  ('block -> blockcontent','block',1,'p_block','_parser.py',17),
  ('block -> blockcontent block','block',2,'p_block_continuation','_parser.py',22),
  ('blockcontent -> text','blockcontent',1,'p_block_text','_parser.py',27),
  ('blockcontent -> tag','blockcontent',1,'p_block_taglist','_parser.py',32),
  ('text -> TEXT','text',1,'p_text','_parser.py',37),
  ('text -> NEWLINE','text',1,'p_text','_parser.py',38),
  ('text -> POSSIBLEINDENT','text',1,'p_text','_parser.py',39),
  ('tag -> TAGOPEN TAGNAME TAGCLOSE','tag',3,'p_tag_simple','_parser.py',46),
  ('tag -> TAGOPEN TAGNAME TAGARGSEP TAGCLOSE','tag',4,'p_tag_withemptyarg','_parser.py',51),
  ('tag -> TAGOPEN TAGNAME TAGARGSEP arglist TAGCLOSE','tag',5,'p_tag_withargs','_parser.py',56),
  ('tag -> TAGOPEN TAGNAME TAGARGSEP NEWLINE INDENT block DEDENT','tag',7,'p_tag_withblockarg','_parser.py',61),
  ('tag -> TAGOPEN TAGNAME TAGARGSEP arglist TAGARGSEP NEWLINE INDENT block DEDENT','tag',9,'p_tag_withargsandblockarg','_parser.py',66),
  ('arglist -> arg','arglist',1,'p_arglist_leaf','_parser.py',72),
  ('arglist -> arglist TAGARGSEP arg','arglist',3,'p_arglist','_parser.py',77),
  ('arg -> argpart','arg',1,'p_arg','_parser.py',82),
  ('arg -> argpart arg','arg',2,'p_arg_continuation','_parser.py',87),
  ('argpart -> TEXT','argpart',1,'p_argpart_text','_parser.py',92),
  ('argpart -> tag','argpart',1,'p_argpart_tag','_parser.py',97),
]
